from __future__ import annotations

import base64
import json
import os
from dataclasses import dataclass, field
from pathlib import Path
from urllib import request as urlrequest

from mira_stylist.models.vton import VTONInputPayload, VTONRunResult


@dataclass(frozen=True)
class RemoteVTONConfig:
    base_url: str = field(default_factory=lambda: os.getenv("MIRA_STYLIST_REMOTE_VTON_URL", "").strip())
    api_path: str = field(default_factory=lambda: os.getenv("MIRA_STYLIST_REMOTE_VTON_API_PATH", "/tryon").strip() or "/tryon")
    timeout_seconds: int = field(default_factory=lambda: int(os.getenv("MIRA_STYLIST_REMOTE_VTON_TIMEOUT_SECONDS", "120")))


class RemoteVTONClient:
    """Call a remote GPU-backed try-on API using base64 JSON payloads."""

    def __init__(self, config: RemoteVTONConfig | None = None) -> None:
        self.config = config or RemoteVTONConfig()

    def run(
        self,
        *,
        payload: VTONInputPayload,
        output_dir: str | Path,
    ) -> VTONRunResult:
        if not self.config.base_url:
            return VTONRunResult(
                status="unavailable",
                backend="remote_gpu_api",
                notes=["MIRA_STYLIST_REMOTE_VTON_URL is not configured."],
            )
        endpoint = self.config.base_url.rstrip("/") + self.config.api_path
        request_body = {
            "user_image": self._base64_file(payload.avatar_image_path),
            "garment_image": self._base64_file(payload.garment_image_path),
            "pose": self._load_json(payload.pose_metadata_path),
            "human_mask": self._base64_file(payload.person_segmentation_path),
            "garment_mask": self._base64_file(payload.garment_mask_path),
            "garment_category": payload.garment_category,
            "garment_color": payload.garment_color,
            "garment_title": payload.garment_title,
        }
        body = json.dumps(request_body).encode("utf-8")
        req = urlrequest.Request(
            endpoint,
            data=body,
            headers={"Content-Type": "application/json"},
            method="POST",
        )
        try:
            with urlrequest.urlopen(req, timeout=self.config.timeout_seconds) as response:
                response_payload = json.loads(response.read().decode("utf-8"))
        except Exception as exc:
            return VTONRunResult(
                status="runtime_error",
                backend="remote_gpu_api",
                notes=[f"Remote VTON request failed: {exc}"],
            )
        output_dir = Path(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)
        preview_bytes = self._extract_image_bytes(response_payload.get("result_image"))
        if not preview_bytes:
            return VTONRunResult(
                status="invalid_runner_output",
                backend="remote_gpu_api",
                notes=["Remote VTON response did not include a result_image payload."],
            )
        result_path = output_dir / "remote_tryon_result.png"
        result_path.write_bytes(preview_bytes)
        meta_path = output_dir / "remote_tryon_response.json"
        meta_path.write_text(json.dumps(response_payload, indent=2), encoding="utf-8")
        return VTONRunResult(
            status="ok",
            backend="remote_gpu_api",
            generated_preview_path=str(result_path),
            generated_auxiliary_paths={"remote_response": str(meta_path)},
            notes=["Generated by remote GPU API backend."],
        )

    @staticmethod
    def _base64_file(path_value: str | None) -> str | None:
        if not path_value:
            return None
        path = Path(path_value)
        if not path.exists():
            return None
        return base64.b64encode(path.read_bytes()).decode("ascii")

    @staticmethod
    def _load_json(path_value: str | None) -> dict | None:
        if not path_value:
            return None
        path = Path(path_value)
        if not path.exists():
            return None
        try:
            return json.loads(path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            return None

    @staticmethod
    def _extract_image_bytes(value: str | None) -> bytes | None:
        if not value:
            return None
        try:
            return base64.b64decode(value)
        except Exception:
            return None
