from __future__ import annotations

import getpass
import os
from dataclasses import dataclass
from pathlib import Path

from mira.config.paths import paths


# First-run wizard. Walks through the four required keys (plus a few opt-in
# ones), writes them to `<config_dir>/.env`, and refuses to overwrite an
# existing non-empty value unless the user explicitly asks to replace it.
#
# Why terminal, not a GUI:
#   * The menu-bar app is an LSUIElement — it has no main window to host a
#     setup screen, and building a one-shot rumps window just for setup is
#     more surface than it's worth.
#   * macOS mic/accessibility permissions are granted via system dialogs we
#     can't replicate anyway; users end up in System Settings either way.
#   * `mira setup` from Terminal is a stable invocation target we can
#     document and re-run if something breaks.


@dataclass(frozen=True)
class KeyPrompt:
    env_name: str
    label: str
    help_url: str
    required: bool
    # Whether to use getpass (hide keystrokes). Voice IDs and usernames are
    # not secret; API keys are.
    secret: bool = True


_PROMPTS: tuple[KeyPrompt, ...] = (
    KeyPrompt(
        env_name="OPENAI_API_KEY",
        label="OpenAI API key (planner + embeddings)",
        help_url="https://platform.openai.com/api-keys",
        required=True,
    ),
    KeyPrompt(
        env_name="PICOVOICE_ACCESS_KEY",
        label="Picovoice access key (wake-word)",
        help_url="https://console.picovoice.ai/",
        required=True,
    ),
    KeyPrompt(
        env_name="DEEPGRAM_API_KEY",
        label="Deepgram API key (streaming STT)",
        help_url="https://console.deepgram.com/",
        required=True,
    ),
    KeyPrompt(
        env_name="CARTESIA_API_KEY",
        label="Cartesia API key (TTS)",
        help_url="https://play.cartesia.ai/",
        required=True,
    ),
    KeyPrompt(
        env_name="CARTESIA_VOICE",
        label="Cartesia voice ID (copied from the voice library)",
        help_url="https://play.cartesia.ai/voices",
        required=True,
        secret=False,
    ),
    KeyPrompt(
        env_name="BRAVE_SEARCH_API_KEY",
        label="Brave Search key (optional — web search tool)",
        help_url="https://api-dashboard.search.brave.com/",
        required=False,
    ),
    KeyPrompt(
        env_name="GROQ_API_KEY",
        label="Groq API key (optional — cheap/fast Tier-0 router)",
        help_url="https://console.groq.com/keys",
        required=False,
    ),
    KeyPrompt(
        env_name="ANTHROPIC_API_KEY",
        label="Anthropic API key (optional — Claude planner)",
        help_url="https://console.anthropic.com/settings/keys",
        required=False,
    ),
    KeyPrompt(
        env_name="USER_NAME",
        label="What should MIRA call you?",
        help_url="",
        required=False,
        secret=False,
    ),
)


def _parse_env_file(path: Path) -> dict[str, str]:
    """Very small `.env` parser — no quoting rules, no interpolation. Good
    enough for the fields we own and keeps us out of dotenv-write land."""
    if not path.exists():
        return {}
    out: dict[str, str] = {}
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, _, v = line.partition("=")
        out[k.strip()] = v.strip().strip('"').strip("'")
    return out


def _write_env_file(path: Path, values: dict[str, str]) -> None:
    """Atomic write so an interrupted wizard can't leave a half-written .env
    that breaks boot. Also chmod 600 since the file holds secrets."""
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    lines = ["# Generated by `mira setup`. Edit by hand if you prefer."]
    for k in sorted(values):
        lines.append(f'{k}="{values[k]}"')
    tmp.write_text("\n".join(lines) + "\n")
    os.chmod(tmp, 0o600)
    tmp.replace(path)


def _prompt_one(p: KeyPrompt, current: str | None) -> str | None:
    """Returns the new value (possibly unchanged), or None to skip.

    Empty input keeps the current value; 'clear' wipes it; anything else
    replaces. Optional keys can be left blank forever."""
    shown_current = "(set)" if current else "(not set)"
    lead = f"\n{p.label}"
    if p.help_url:
        lead += f"  →  {p.help_url}"
    print(lead)
    print(f"  env: {p.env_name}   current: {shown_current}")

    prompt = "  value (blank = keep, 'clear' = remove): "
    raw = getpass.getpass(prompt) if p.secret else input(prompt)
    raw = raw.strip()
    if raw == "":
        return current
    if raw.lower() == "clear":
        return None
    return raw


def run_wizard(*, env_path: Path | None = None) -> int:
    """Interactive setup. Returns exit code (0 = success, 1 = aborted)."""
    target = env_path or (paths.config_dir / ".env")
    existing = _parse_env_file(target)

    print("MIRA setup")
    print(f"  config file: {target}")
    print(
        "  Leave any prompt blank to keep the existing value. Type 'clear' "
        "to remove one. Ctrl-C to abort without writing."
    )

    updated = dict(existing)
    try:
        for prompt in _PROMPTS:
            new_val = _prompt_one(prompt, existing.get(prompt.env_name))
            if new_val is None:
                updated.pop(prompt.env_name, None)
            else:
                updated[prompt.env_name] = new_val
    except (KeyboardInterrupt, EOFError):
        print("\nAborted. No changes written.")
        return 1

    # Only rewrite if something actually changed — avoids bumping mtime and
    # churning file-watcher reloads for a purely informational re-run.
    if updated == existing:
        print("\nNo changes. .env left as-is.")
        return 0

    _write_env_file(target, updated)
    print(f"\nWrote {target} (chmod 600).")

    missing = [p.env_name for p in _PROMPTS if p.required and not updated.get(p.env_name)]
    if missing:
        print(
            "  Still missing required keys: " + ", ".join(missing) + "\n"
            "  Run `mira setup` again or edit the file directly."
        )
        return 1
    print("  All required keys are set. Run `mira doctor` to verify.")
    return 0
