from __future__ import annotations

from mira_stylist.models import (
    LookComparisonFeedback,
    PairingSuggestion,
    PreviewRenderJob,
    PreviewStatus,
    RemoteTryOnStatus,
    SingleLookFeedback,
    StylistTryOnJob,
    TryOnPreviewRequest,
    TryOnRequest,
    TryOnResult,
    UserAvatar,
)
from mira_stylist.models.garment import GarmentItem
from mira_stylist.models.common import utc_now
from mira_stylist.pipelines import PreviewGenerationPipeline
from mira_stylist.utils.ids import new_prefixed_id

from .storage_service import AssetStorageService
from .stylist_commentary_service import StylistCommentaryService
from .artifact_manifest_service import ArtifactManifestService
from .preprocessing_service import PreprocessingService
from .stylist_job_service import StylistJobService
from .tryon_pipeline_orchestrator import TryOnPipelineOrchestrator
from .vton_service import VTONService


class TryOnPreviewService:
    """Create preview jobs that combine avatar state with garment assets."""

    def __init__(
        self,
        storage: AssetStorageService,
        pipeline: PreviewGenerationPipeline | None = None,
        commentary: StylistCommentaryService | None = None,
        vton: VTONService | None = None,
        preprocessing: PreprocessingService | None = None,
        jobs: StylistJobService | None = None,
        manifests: ArtifactManifestService | None = None,
        orchestrator: TryOnPipelineOrchestrator | None = None,
    ):
        self.storage = storage
        self.pipeline = pipeline or PreviewGenerationPipeline()
        self.commentary = commentary or StylistCommentaryService()
        self.vton = vton or VTONService()
        self.preprocessing = preprocessing or PreprocessingService()
        self.jobs = jobs or StylistJobService(storage=storage)
        self.manifests = manifests or ArtifactManifestService(storage=storage)
        self.orchestrator = orchestrator or TryOnPipelineOrchestrator(
            jobs=self.jobs,
            manifests=self.manifests,
            preprocessing=self.preprocessing,
            vton=self.vton,
        )
        self._jobs: dict[str, PreviewRenderJob] = {}
        self._results: dict[str, dict] = {}
        self._load_existing_jobs()

    def create_preview_job(
        self,
        request: TryOnPreviewRequest,
        avatar: UserAvatar,
        garment: GarmentItem,
    ) -> PreviewRenderJob:
        """
        Queue and resolve a preview request.

        TODO:
        - move preview generation to async workers
        - add render retries and artifact versioning
        - support multi-garment outfits and layer ordering
        """

        job_id = new_prefixed_id("tryon")
        storage_paths = self.storage.ensure_tryon_paths(job_id)
        tryon_request = TryOnRequest(
            avatar_id=request.avatar_id,
            garment_id=request.garment_id,
            pose=request.pose,
            camera_angle=request.camera_angle,
            render_mode=request.render_mode,
            notes=request.notes,
        )
        initial_job = PreviewRenderJob(job_id=job_id, request=tryon_request)
        self.storage.write_metadata(storage_paths.metadata_dir / "job.json", initial_job)
        self._jobs[job_id] = initial_job

        initial_job.preview_status = PreviewStatus.PROCESSING
        initial_job.updated_at = utc_now()
        self.storage.write_metadata(storage_paths.metadata_dir / "job.json", initial_job)
        artifacts = self.pipeline.create_preview(
            job_id=job_id,
            request=tryon_request,
            avatar=avatar,
            garment=garment,
            storage_paths=storage_paths,
        )
        orchestration = self.orchestrator.run_sync(
            preview_job_id=job_id,
            request=tryon_request,
            avatar=avatar,
            garment=garment,
            storage_paths=storage_paths,
        )
        vton_result = orchestration.vton_result
        artifacts.result.output_asset_paths["artifact_manifest"] = str(storage_paths.metadata_dir / "artifact_manifest.json")
        artifacts.result.output_asset_paths["stylist_job"] = str(storage_paths.jobs_dir / f"{orchestration.stylist_job.stylist_job_id}.json")
        if vton_result and vton_result.status == "ok" and vton_result.generated_preview_path:
            artifacts.result.output_asset_paths["preview_front"] = vton_result.generated_preview_path
            for key, value in vton_result.generated_auxiliary_paths.items():
                artifacts.result.output_asset_paths[key] = value
            artifacts.result.output_asset_paths["vton_metadata"] = str(storage_paths.metadata_dir / "vton_result.json")
            artifacts.result.notes.insert(0, f"Primary front preview generated by VTON backend: {vton_result.backend}.")
            artifacts.result.notes.insert(
                1,
                f"Preprocessing artifacts persisted at {storage_paths.metadata_dir / 'artifact_manifest.json'}.",
            )
            artifacts.result.fit_assessment.notes.insert(
                0,
                "Front view was generated through the VTON adapter path using avatar photo, person mask, pose keypoints, and garment assets.",
            )
        elif vton_result:
            artifacts.result.output_asset_paths["vton_metadata"] = str(storage_paths.metadata_dir / "vton_result.json")
            artifacts.result.notes.append(f"VTON adapter did not produce a front preview: {vton_result.status}.")
        else:
            artifacts.result.notes.append("Remote-GPU-compatible artifact manifest was created, but no VTON payload could be built for this garment category.")
        artifacts.result.stylist_commentary = self.commentary.build_commentary(
            avatar=avatar,
            garment=garment,
            request=tryon_request,
            fit_assessment=artifacts.result.fit_assessment,
        )
        artifacts.result.updated_at = utc_now()
        artifacts.job.result = artifacts.result
        artifacts.job.updated_at = utc_now()
        self.storage.write_metadata(storage_paths.metadata_dir / "job.json", artifacts.job)
        self.storage.write_metadata(storage_paths.metadata_dir / "result.json", artifacts.result)
        self._jobs[job_id] = artifacts.job
        self._results[job_id] = {
            "preview_front": artifacts.result.output_asset_paths.get("preview_front"),
            "preview_side": artifacts.result.output_asset_paths.get("preview_side"),
            "commentary_summary": artifacts.result.stylist_commentary.summary if artifacts.result.stylist_commentary else None,
        }
        return artifacts.job

    def create_preview_job_async(
        self,
        request: TryOnPreviewRequest,
        avatar: UserAvatar,
        garment: GarmentItem,
    ) -> StylistTryOnJob:
        preview_job_id = new_prefixed_id("tryon")
        storage_paths = self.storage.ensure_tryon_paths(preview_job_id)
        tryon_request = TryOnRequest(
            avatar_id=request.avatar_id,
            garment_id=request.garment_id,
            pose=request.pose,
            camera_angle=request.camera_angle,
            render_mode=request.render_mode,
            notes=request.notes,
        )
        preview_job = PreviewRenderJob(
            job_id=preview_job_id,
            request=tryon_request,
            preview_status=PreviewStatus.PROCESSING,
        )
        self.storage.write_metadata(storage_paths.metadata_dir / "job.json", preview_job)
        self._jobs[preview_job_id] = preview_job
        run = self.orchestrator.submit_async(
            preview_job_id=preview_job_id,
            request=tryon_request,
            avatar=avatar,
            garment=garment,
            storage_paths=storage_paths,
        )
        return run.stylist_job

    def get_job(self, job_id: str) -> PreviewRenderJob | None:
        job = self._jobs.get(job_id)
        if job:
            return job
        return self._load_job_from_disk(job_id)

    def get_pipeline_job(self, stylist_job_id: str) -> StylistTryOnJob | None:
        return self.jobs.get_job(stylist_job_id)

    def poll_pipeline_job(self, stylist_job_id: str) -> StylistTryOnJob | None:
        stylist_job = self.jobs.get_job(stylist_job_id)
        if not stylist_job:
            return None
        storage_paths = self.storage.ensure_tryon_paths(stylist_job.preview_job_id)
        status = self.orchestrator.poll_async(stylist_job=stylist_job, storage_paths=storage_paths)
        updated = self.jobs.get_job(stylist_job_id)
        if status and updated:
            self._apply_pipeline_status_to_preview(updated, status)
        return updated

    def apply_pipeline_callback(
        self,
        *,
        stylist_job_id: str,
        callback_token: str,
        status: RemoteTryOnStatus,
    ) -> StylistTryOnJob | None:
        stylist_job = self.jobs.get_job(stylist_job_id)
        if not stylist_job or stylist_job.callback_token != callback_token:
            return None
        storage_paths = self.storage.ensure_tryon_paths(stylist_job.preview_job_id)
        updated = self.orchestrator.apply_callback(
            stylist_job=stylist_job,
            storage_paths=storage_paths,
            status=status,
        )
        self._apply_pipeline_status_to_preview(updated, status)
        return updated

    def build_single_look_feedback(
        self,
        *,
        job_id: str,
        avatar: UserAvatar,
        garment: GarmentItem,
        question: str | None,
        occasion: str | None,
        style_goal: str | None,
    ) -> SingleLookFeedback:
        job = self.get_job(job_id)
        if not job or not job.result or not job.result.stylist_commentary:
            raise ValueError("Preview job commentary is not available for this look.")
        return self.commentary.answer_single_look_question(
            job_id=job_id,
            avatar=avatar,
            garment=garment,
            request=job.request,
            commentary=job.result.stylist_commentary,
            question=question,
            occasion=occasion,
            style_goal=style_goal,
        )

    def compare_looks(
        self,
        *,
        primary_job_id: str,
        secondary_job_id: str,
        primary_avatar: UserAvatar,
        secondary_avatar: UserAvatar,
        primary_garment: GarmentItem,
        secondary_garment: GarmentItem,
        occasion: str | None,
        style_goal: str | None,
    ) -> LookComparisonFeedback:
        primary_job = self.get_job(primary_job_id)
        secondary_job = self.get_job(secondary_job_id)
        if not primary_job or not secondary_job:
            raise ValueError("One or both preview jobs were not found.")
        if not primary_job.result or not primary_job.result.stylist_commentary:
            raise ValueError("Primary look commentary is not available.")
        if not secondary_job.result or not secondary_job.result.stylist_commentary:
            raise ValueError("Secondary look commentary is not available.")
        return self.commentary.compare_looks(
            primary_job_id=primary_job_id,
            secondary_job_id=secondary_job_id,
            primary_avatar=primary_avatar,
            secondary_avatar=secondary_avatar,
            primary_garment=primary_garment,
            secondary_garment=secondary_garment,
            primary_commentary=primary_job.result.stylist_commentary,
            secondary_commentary=secondary_job.result.stylist_commentary,
            primary_request=primary_job.request,
            secondary_request=secondary_job.request,
            occasion=occasion,
            style_goal=style_goal,
        )

    def suggest_pairings(
        self,
        *,
        avatar: UserAvatar,
        garment: GarmentItem,
        occasion: str | None,
        style_goal: str | None,
        weather_hint: str | None,
    ) -> PairingSuggestion:
        return self.commentary.suggest_pairings(
            avatar=avatar,
            garment=garment,
            occasion=occasion,
            style_goal=style_goal,
            weather_hint=weather_hint,
        )

    def _load_existing_jobs(self) -> None:
        for path in self.storage.glob("tryon/*/metadata/job.json"):
            job = self.storage.read_model(path, PreviewRenderJob)
            if not job:
                continue
            self._jobs[job.job_id] = job
            if job.result:
                self._results[job.job_id] = dict(job.result.output_asset_paths)

    def _load_job_from_disk(self, job_id: str) -> PreviewRenderJob | None:
        matches = self.storage.glob(f"tryon/{job_id}/metadata/job.json")
        if not matches:
            return None
        job = self.storage.read_model(matches[0], PreviewRenderJob)
        if not job:
            return None
        self._jobs[job_id] = job
        if job.result:
            self._results[job_id] = dict(job.result.output_asset_paths)
        return job

    def _apply_pipeline_status_to_preview(self, stylist_job: StylistTryOnJob, status: RemoteTryOnStatus) -> None:
        preview_job = self.get_job(stylist_job.preview_job_id)
        if not preview_job:
            return
        preview_job.updated_at = utc_now()
        if status.status in {"queued", "running", "processing"}:
            preview_job.preview_status = PreviewStatus.PROCESSING
        elif status.status == "completed":
            preview_job.preview_status = PreviewStatus.COMPLETED
            if not preview_job.result:
                preview_job.result = TryOnResult(
                    job_id=preview_job.job_id,
                    avatar_id=preview_job.request.avatar_id,
                    garment_id=preview_job.request.garment_id,
                )
            preview_job.result.preview_status = PreviewStatus.COMPLETED
            if status.result_image_url:
                preview_job.result.output_asset_paths["preview_front"] = status.result_image_url
            preview_job.result.notes.extend(status.notes)
            preview_job.result.updated_at = utc_now()
        else:
            preview_job.preview_status = PreviewStatus.FAILED
            if not preview_job.result:
                preview_job.result = TryOnResult(
                    job_id=preview_job.job_id,
                    avatar_id=preview_job.request.avatar_id,
                    garment_id=preview_job.request.garment_id,
                )
            preview_job.result.preview_status = PreviewStatus.FAILED
            preview_job.result.notes.extend(status.notes)
            preview_job.result.updated_at = utc_now()
        storage_paths = self.storage.ensure_tryon_paths(preview_job.job_id)
        self.storage.write_metadata(storage_paths.metadata_dir / "job.json", preview_job)
        self._jobs[preview_job.job_id] = preview_job
