from __future__ import annotations

import base64
import hashlib
import json
import mimetypes
import subprocess
from dataclasses import dataclass
from pathlib import Path
from urllib.parse import quote

from mira_stylist.models.avatar import BodyProfile, UserAvatar
from mira_stylist.models.common import PreviewStatus
from mira_stylist.models.garment import GarmentCategory, GarmentItem
from mira_stylist.models.outfit import OutfitComponent, OutfitComponentSourceKind
from mira_stylist.models.tryon import FitAssessment, PreviewRenderJob, TryOnRequest, TryOnResult
from mira_stylist.utils import inspect_image_bytes
from mira_stylist.utils.paths import OutfitStoragePaths, TryOnStoragePaths


@dataclass(frozen=True)
class PreviewArtifacts:
    job: PreviewRenderJob
    result: TryOnResult


class PreviewGenerationPipeline:
    """Lightweight MVP preview generator for avatar-garment overlay jobs."""

    def create_preview(
        self,
        job_id: str,
        request: TryOnRequest,
        avatar: UserAvatar,
        garment: GarmentItem,
        storage_paths: TryOnStoragePaths,
    ) -> PreviewArtifacts:
        """
        Produce a deterministic 2D composition artifact.

        TODO:
        - body-garment compatibility scoring
        - pose-aware cloth alignment and deformation
        - neural try-on or mesh-based overlay selection
        - AR-optimized render export for phone playback
        """

        fit_confidence = self._fit_confidence(avatar, garment)
        fit = FitAssessment(
            fit_confidence=fit_confidence,
            estimated_size_alignment=self._size_alignment(garment),
            occlusion_risk="high" if garment.confidence_scores.get("background_complexity", 0.0) > 0.5 else "low",
            notes=[
                "This preview is an MVP 2D composition, not a physically realistic try-on.",
                "Garment placement is category-aware and measurement-aware, but not segmented or simulated.",
                "Future versions should score silhouette fit, tension zones, and pose stability.",
            ],
        )

        preview_front = storage_paths.previews_dir / "front_overlay.svg"
        preview_side = storage_paths.previews_dir / "side_overlay.svg"
        preview_manifest = storage_paths.metadata_dir / "render_manifest.json"
        preview_front.write_text(
            self._preview_svg(avatar, garment, request, view="front", fit_confidence=fit_confidence),
            encoding="utf-8",
        )
        preview_side.write_text(
            self._preview_svg(avatar, garment, request, view="side", fit_confidence=fit_confidence),
            encoding="utf-8",
        )
        preview_manifest.write_text(
            json.dumps(
                {
                    "job_id": job_id,
                    "avatar_id": avatar.avatar_id,
                    "garment_id": garment.garment_id,
                    "render_mode": request.render_mode.value,
                    "camera_angle": request.camera_angle.value,
                    "composition_mode": "category_aware_svg_overlay",
                    "note": "MVP 2D composition manifest.",
                },
                indent=2,
            ),
            encoding="utf-8",
        )

        result = TryOnResult(
            job_id=job_id,
            avatar_id=avatar.avatar_id,
            garment_id=garment.garment_id,
            preview_status=PreviewStatus.COMPLETED,
            fit_assessment=fit,
            output_asset_paths={
                "preview_front": str(preview_front),
                "preview_side": str(preview_side),
                "metadata": str(preview_manifest),
            },
            notes=[
                "Generated by category-aware lightweight SVG preview pipeline.",
                f"Render mode: {request.render_mode.value}",
                f"Camera angle: {request.camera_angle.value}",
            ],
        )

        job = PreviewRenderJob(
            job_id=job_id,
            request=request,
            preview_status=PreviewStatus.COMPLETED,
            result=result,
        )

        return PreviewArtifacts(job=job, result=result)

    def create_outfit_preview(
        self,
        *,
        outfit_id: str,
        avatar: UserAvatar,
        anchor_garment: GarmentItem,
        components: list[OutfitComponent],
        storage_paths: OutfitStoragePaths,
        render_mode,
        camera_angle: str,
        occasion: str | None,
        style_goal: str | None,
    ) -> dict[str, str]:
        preview_front = storage_paths.previews_dir / "front_outfit.svg"
        preview_side = storage_paths.previews_dir / "side_outfit.svg"
        preview_manifest = storage_paths.metadata_dir / "outfit_render_manifest.json"
        preview_front.write_text(
            self._outfit_preview_svg(
                avatar=avatar,
                anchor_garment=anchor_garment,
                components=components,
                render_mode=str(getattr(render_mode, "value", render_mode)),
                view="front",
                camera_angle=camera_angle,
                occasion=occasion,
                style_goal=style_goal,
            ),
            encoding="utf-8",
        )
        preview_side.write_text(
            self._outfit_preview_svg(
                avatar=avatar,
                anchor_garment=anchor_garment,
                components=components,
                render_mode=str(getattr(render_mode, "value", render_mode)),
                view="side",
                camera_angle=camera_angle,
                occasion=occasion,
                style_goal=style_goal,
            ),
            encoding="utf-8",
        )
        preview_manifest.write_text(
            json.dumps(
                {
                    "outfit_id": outfit_id,
                    "avatar_id": avatar.avatar_id,
                    "anchor_garment_id": anchor_garment.garment_id,
                    "component_count": len(components),
                    "camera_angle": camera_angle,
                    "render_mode": str(getattr(render_mode, "value", render_mode)),
                    "occasion": occasion,
                    "style_goal": style_goal,
                    "composition_mode": "multi_garment_svg_composition",
                    "note": "MVP composed look preview using one real anchor garment and generated companions.",
                },
                indent=2,
            ),
            encoding="utf-8",
        )
        return {
            "preview_front": str(preview_front),
            "preview_side": str(preview_side),
            "metadata": str(preview_manifest),
        }

    @staticmethod
    def _fit_confidence(avatar: UserAvatar, garment: GarmentItem) -> float:
        measurement_signal = 0.0
        profile_signal = 0.0
        if avatar.measurements.height_cm:
            measurement_signal += 0.12
        if avatar.measurements.waist_cm or avatar.measurements.chest_cm or avatar.measurements.hips_cm:
            measurement_signal += 0.12
        if getattr(avatar, "body_profile", None):
            profile_signal = min(avatar.body_profile.profile_confidence * 0.12, 0.1)
        garment_signal = min(garment.confidence_scores.get("candidate_selection", 0.45), 0.35)
        return round(min(0.35 + measurement_signal + profile_signal + garment_signal, 0.84), 2)

    @staticmethod
    def _size_alignment(garment: GarmentItem) -> str:
        return "unverified" if garment.size_info else "unknown"

    def _preview_svg(
        self,
        avatar: UserAvatar,
        garment: GarmentItem,
        request: TryOnRequest,
        *,
        view: str,
        fit_confidence: float,
    ) -> str:
        capture = self._capture_asset(avatar=avatar, view=view)
        if capture:
            return self._photo_grounded_single_preview(
                avatar=avatar,
                garment=garment,
                request=request,
                fit_confidence=fit_confidence,
                view=view,
                capture=capture,
            )
        palette = self._palette(color=garment.color, title=garment.title, seed_id=garment.garment_id)
        body = self._body_metrics(avatar, view=view)
        garment_shape = self._garment_shape(
            category=garment.category,
            body=body,
            render_mode=request.render_mode.value,
            palette=palette,
            label=garment.title,
            emphasis="primary",
        )
        garment_label = self._escape(garment.title)
        color_label = self._escape(garment.color or "unknown")
        view_label = self._escape(view)
        pose_label = self._escape(request.pose)
        category_label = self._escape(garment.category.value)
        frame_label = self._escape(avatar.body_profile.body_frame)
        posture_label = self._escape(avatar.body_profile.posture_hint)
        return (
            "<svg xmlns='http://www.w3.org/2000/svg' width='768' height='1280' viewBox='0 0 768 1280'>"
            "<defs>"
            "<linearGradient id='bg' x1='0' y1='0' x2='1' y2='1'>"
            "<stop offset='0%' stop-color='#fbf7f1'/>"
            "<stop offset='100%' stop-color='#efe5d8'/>"
            "</linearGradient>"
            f"<linearGradient id='garment' x1='0' y1='0' x2='0' y2='1'><stop offset='0%' stop-color='{palette['primary']}'/><stop offset='100%' stop-color='{palette['secondary']}'/></linearGradient>"
            "</defs>"
            "<rect width='100%' height='100%' fill='url(#bg)'/>"
            "<rect x='38' y='40' width='692' height='1200' rx='28' fill='#fffaf5' stroke='#d8cab8'/>"
            "<text x='64' y='92' font-size='30' font-family='Arial' fill='#2f261f'>MIRA Stylist Preview</text>"
            f"<text x='64' y='126' font-size='18' font-family='Arial' fill='#66584d'>view={view_label} pose={pose_label} render={self._escape(request.render_mode.value)}</text>"
            f"<text x='64' y='156' font-size='18' font-family='Arial' fill='#66584d'>garment={garment_label} category={category_label} color={color_label}</text>"
            f"<text x='64' y='186' font-size='18' font-family='Arial' fill='#66584d'>frame={frame_label} posture={posture_label} profile_conf={avatar.body_profile.profile_confidence:.2f}</text>"
            f"{self._avatar_base_svg(body)}"
            f"{garment_shape}"
            f"<text x='64' y='1138' font-size='22' font-family='Arial' fill='#2f261f'>fit confidence {fit_confidence:.2f}</text>"
            "<text x='64' y='1174' font-size='17' font-family='Arial' fill='#66584d'>MVP 2D overlay only. No body reconstruction, segmentation, or cloth simulation.</text>"
            f"<text x='64' y='1206' font-size='17' font-family='Arial' fill='#66584d'>avatar={self._escape(avatar.avatar_id)} garment={self._escape(garment.garment_id)}</text>"
            "</svg>"
        )

    def _outfit_preview_svg(
        self,
        *,
        avatar: UserAvatar,
        anchor_garment: GarmentItem,
        components: list[OutfitComponent],
        render_mode: str,
        view: str,
        camera_angle: str,
        occasion: str | None,
        style_goal: str | None,
    ) -> str:
        capture = self._capture_asset(avatar=avatar, view=view)
        if capture:
            return self._photo_grounded_outfit_preview(
                avatar=avatar,
                anchor_garment=anchor_garment,
                components=components,
                render_mode=render_mode,
                view=view,
                camera_angle=camera_angle,
                occasion=occasion,
                style_goal=style_goal,
                capture=capture,
            )
        body = self._body_metrics(avatar, view=view)
        shapes: list[str] = []
        component_labels: list[str] = []
        for component in sorted(components, key=lambda item: item.layer_order):
            palette = self._palette(
                color=component.color,
                title=component.label,
                seed_id=component.component_id,
            )
            shapes.append(
                self._garment_shape(
                    category=component.category,
                    body=body,
                    render_mode=render_mode,
                    palette=palette,
                    label=component.label,
                    role=component.role,
                    source_kind=component.source_kind.value,
                    emphasis="primary" if component.source_kind == OutfitComponentSourceKind.ANCHOR_GARMENT else "companion",
                )
            )
            component_labels.append(f"{component.category.value}:{self._escape(component.label)}")

        summary = f"occasion={self._escape(occasion or 'open')} goal={self._escape(style_goal or 'balanced')}"
        return (
            "<svg xmlns='http://www.w3.org/2000/svg' width='768' height='1280' viewBox='0 0 768 1280'>"
            "<defs>"
            "<linearGradient id='bg' x1='0' y1='0' x2='1' y2='1'>"
            "<stop offset='0%' stop-color='#fbf7f1'/>"
            "<stop offset='100%' stop-color='#efe5d8'/>"
            "</linearGradient>"
            "</defs>"
            "<rect width='100%' height='100%' fill='url(#bg)'/>"
            "<rect x='38' y='40' width='692' height='1200' rx='28' fill='#fffaf5' stroke='#d8cab8'/>"
            "<text x='64' y='92' font-size='30' font-family='Arial' fill='#2f261f'>MIRA Stylist Outfit Preview</text>"
            f"<text x='64' y='126' font-size='18' font-family='Arial' fill='#66584d'>view={self._escape(view)} camera={self._escape(camera_angle)} render={self._escape(render_mode)}</text>"
            f"<text x='64' y='156' font-size='18' font-family='Arial' fill='#66584d'>anchor={self._escape(anchor_garment.title)} summary={summary}</text>"
            f"<text x='64' y='186' font-size='18' font-family='Arial' fill='#66584d'>components={'; '.join(component_labels[:4])} anchor_mode={self._escape(str(body['anchor_mode']))}</text>"
            f"{self._avatar_base_svg(body)}"
            f"{''.join(shapes)}"
            f"<text x='64' y='1138' font-size='22' font-family='Arial' fill='#2f261f'>composed look with {len(components)} pieces</text>"
            "<text x='64' y='1174' font-size='17' font-family='Arial' fill='#66584d'>Companion pieces are generated styling placeholders, not real wardrobe assets yet.</text>"
            f"<text x='64' y='1206' font-size='17' font-family='Arial' fill='#66584d'>avatar={self._escape(avatar.avatar_id)} anchor={self._escape(anchor_garment.garment_id)}</text>"
            "</svg>"
        )

    def _photo_grounded_single_preview(
        self,
        *,
        avatar: UserAvatar,
        garment: GarmentItem,
        request: TryOnRequest,
        fit_confidence: float,
        view: str,
        capture: dict[str, str | int | float],
    ) -> str:
        palette = self._palette(color=garment.color, title=garment.title, seed_id=garment.garment_id)
        layout = self._photo_layout(int(capture["width"]), int(capture["height"]))
        body = self._photo_body_metrics(avatar, view=view, layout=layout)
        segmentation = self._load_segmentation_analysis(avatar, view=view)
        person_mask_defs, person_mask_id, segmentation_mode = self._person_mask_svg(segmentation=segmentation, layout=layout)
        garment_texture = self._garment_texture_asset(garment)
        replacement_layer, replacement_mode = self._photo_replacement_layer(
            garment=garment,
            body=body,
            palette=palette,
            overlay_id=f"{garment.garment_id}_{view}",
            person_mask_id=person_mask_id,
        )
        garment_overlay, texture_mode = self._photo_grounded_primary_overlay(
            garment=garment,
            body=body,
            render_mode=request.render_mode.value,
            palette=palette,
            texture=garment_texture,
            overlay_id=f"{garment.garment_id}_{view}",
            person_mask_id=person_mask_id,
        )
        return (
            "<svg xmlns='http://www.w3.org/2000/svg' width='768' height='1280' viewBox='0 0 768 1280'>"
            "<defs>"
            "<linearGradient id='bg' x1='0' y1='0' x2='1' y2='1'>"
            "<stop offset='0%' stop-color='#fbf7f1'/>"
            "<stop offset='100%' stop-color='#efe5d8'/>"
            "</linearGradient>"
            f"{person_mask_defs}"
            "</defs>"
            "<rect width='100%' height='100%' fill='url(#bg)'/>"
            "<rect x='38' y='40' width='692' height='1200' rx='28' fill='#fffaf5' stroke='#d8cab8'/>"
            "<text x='64' y='92' font-size='30' font-family='Arial' fill='#2f261f'>MIRA Stylist Photo Grounded Preview</text>"
            f"<text x='64' y='126' font-size='18' font-family='Arial' fill='#66584d'>view={self._escape(view)} render={self._escape(request.render_mode.value)} composition=photo_grounded</text>"
            f"<text x='64' y='156' font-size='18' font-family='Arial' fill='#66584d'>garment={self._escape(garment.title)} category={self._escape(garment.category.value)} color={self._escape(garment.color or 'unknown')} texture={self._escape(texture_mode)} mask-source={self._escape(segmentation_mode)}</text>"
            f"<text x='64' y='186' font-size='18' font-family='Arial' fill='#66584d'>frame={self._escape(avatar.body_profile.body_frame)} posture={self._escape(avatar.body_profile.posture_hint)} profile_conf={avatar.body_profile.profile_confidence:.2f} anchor_mode={self._escape(str(body['anchor_mode']))} replacement={self._escape(replacement_mode)}</text>"
            f"<rect x='{layout['frame_x']:.1f}' y='{layout['frame_y']:.1f}' width='{layout['frame_w']:.1f}' height='{layout['frame_h']:.1f}' rx='26' fill='#f2ebe2' stroke='#d6c7b7'/>"
            f"<image href='{capture['data_uri']}' x='{layout['image_x']:.1f}' y='{layout['image_y']:.1f}' width='{layout['image_w']:.1f}' height='{layout['image_h']:.1f}' preserveAspectRatio='none'/>"
            f"<rect x='{layout['image_x']:.1f}' y='{layout['image_y']:.1f}' width='{layout['image_w']:.1f}' height='{layout['image_h']:.1f}' rx='22' fill='#fff7ef' opacity='0.08'/>"
            f"{replacement_layer}"
            f"{garment_overlay}"
            f"<text x='64' y='1138' font-size='22' font-family='Arial' fill='#2f261f'>fit confidence {fit_confidence:.2f}</text>"
            f"<text x='64' y='1174' font-size='17' font-family='Arial' fill='#66584d'>Photo-grounded overlay uses your uploaded image as the base when the capture format is browser-renderable.</text>"
            f"<text x='64' y='1206' font-size='17' font-family='Arial' fill='#66584d'>capture_mime={self._escape(str(capture['mime']))} avatar={self._escape(avatar.avatar_id)} garment={self._escape(garment.garment_id)}</text>"
            "</svg>"
        )

    def _photo_grounded_outfit_preview(
        self,
        *,
        avatar: UserAvatar,
        anchor_garment: GarmentItem,
        components: list[OutfitComponent],
        render_mode: str,
        view: str,
        camera_angle: str,
        occasion: str | None,
        style_goal: str | None,
        capture: dict[str, str | int | float],
    ) -> str:
        layout = self._photo_layout(int(capture["width"]), int(capture["height"]))
        body = self._photo_body_metrics(avatar, view=view, layout=layout)
        segmentation = self._load_segmentation_analysis(avatar, view=view)
        person_mask_defs, person_mask_id, segmentation_mode = self._person_mask_svg(segmentation=segmentation, layout=layout)
        shapes: list[str] = []
        component_labels: list[str] = []
        anchor_texture = self._garment_texture_asset(anchor_garment)
        anchor_texture_mode = "template_fallback"
        replacement_layer, replacement_mode = self._photo_replacement_layer(
            garment=anchor_garment,
            body=body,
            palette=self._palette(color=anchor_garment.color, title=anchor_garment.title, seed_id=anchor_garment.garment_id),
            overlay_id=f"{anchor_garment.garment_id}_{view}_replace",
            person_mask_id=person_mask_id,
        )
        for component in sorted(components, key=lambda item: item.layer_order):
            palette = self._palette(
                color=component.color,
                title=component.label,
                seed_id=component.component_id,
            )
            if component.source_kind == OutfitComponentSourceKind.ANCHOR_GARMENT:
                overlay_markup, anchor_texture_mode = self._photo_grounded_primary_overlay(
                    garment=anchor_garment,
                    body=body,
                    render_mode=render_mode,
                    palette=palette,
                    texture=anchor_texture,
                    overlay_id=f"{anchor_garment.garment_id}_{view}_outfit",
                    role=component.role,
                    person_mask_id=person_mask_id,
                )
                shapes.append(overlay_markup)
            else:
                shapes.append(
                    self._garment_shape(
                        category=component.category,
                        body=body,
                        render_mode=render_mode,
                        palette=palette,
                        label=component.label,
                        role=component.role,
                        source_kind=component.source_kind.value,
                        emphasis="companion",
                    )
                )
            component_labels.append(f"{component.category.value}:{self._escape(component.label)}")
        return (
            "<svg xmlns='http://www.w3.org/2000/svg' width='768' height='1280' viewBox='0 0 768 1280'>"
            "<defs>"
            "<linearGradient id='bg' x1='0' y1='0' x2='1' y2='1'>"
            "<stop offset='0%' stop-color='#fbf7f1'/>"
            "<stop offset='100%' stop-color='#efe5d8'/>"
            "</linearGradient>"
            f"{person_mask_defs}"
            "</defs>"
            "<rect width='100%' height='100%' fill='url(#bg)'/>"
            "<rect x='38' y='40' width='692' height='1200' rx='28' fill='#fffaf5' stroke='#d8cab8'/>"
            "<text x='64' y='92' font-size='30' font-family='Arial' fill='#2f261f'>MIRA Stylist Photo Grounded Outfit Preview</text>"
            f"<text x='64' y='126' font-size='18' font-family='Arial' fill='#66584d'>view={self._escape(view)} camera={self._escape(camera_angle)} render={self._escape(render_mode)} composition=photo_grounded</text>"
            f"<text x='64' y='156' font-size='18' font-family='Arial' fill='#66584d'>anchor={self._escape(anchor_garment.title)} occasion={self._escape(occasion or 'open')} goal={self._escape(style_goal or 'balanced')} texture={self._escape(anchor_texture_mode)} mask-source={self._escape(segmentation_mode)}</text>"
            f"<text x='64' y='186' font-size='18' font-family='Arial' fill='#66584d'>components={'; '.join(component_labels[:4])} anchor_mode={self._escape(str(body['anchor_mode']))} replacement={self._escape(replacement_mode)}</text>"
            f"<rect x='{layout['frame_x']:.1f}' y='{layout['frame_y']:.1f}' width='{layout['frame_w']:.1f}' height='{layout['frame_h']:.1f}' rx='26' fill='#f2ebe2' stroke='#d6c7b7'/>"
            f"<image href='{capture['data_uri']}' x='{layout['image_x']:.1f}' y='{layout['image_y']:.1f}' width='{layout['image_w']:.1f}' height='{layout['image_h']:.1f}' preserveAspectRatio='none'/>"
            f"<rect x='{layout['image_x']:.1f}' y='{layout['image_y']:.1f}' width='{layout['image_w']:.1f}' height='{layout['image_h']:.1f}' rx='22' fill='#fff7ef' opacity='0.08'/>"
            f"{replacement_layer}"
            f"{''.join(shapes)}"
            f"<text x='64' y='1138' font-size='22' font-family='Arial' fill='#2f261f'>composed look with {len(components)} pieces</text>"
            "<text x='64' y='1174' font-size='17' font-family='Arial' fill='#66584d'>Companion pieces are generated styling placeholders layered over your uploaded photo.</text>"
            f"<text x='64' y='1206' font-size='17' font-family='Arial' fill='#66584d'>capture_mime={self._escape(str(capture['mime']))} avatar={self._escape(avatar.avatar_id)} anchor={self._escape(anchor_garment.garment_id)}</text>"
            "</svg>"
        )

    @staticmethod
    def _escape(value: str) -> str:
        return (
            value.replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace('"', "&quot;")
            .replace("'", "&apos;")
        )

    def _palette(self, *, color: str | None, title: str, seed_id: str) -> dict[str, str]:
        seed = (color or title or seed_id).lower().encode("utf-8")
        digest = hashlib.sha256(seed).hexdigest()
        hue = int(digest[:2], 16)
        if color:
            color_name = color.lower()
            if "black" in color_name:
                return {"primary": "#3b3734", "secondary": "#6f6862", "accent": "#bcaea2"}
            if "blue" in color_name:
                return {"primary": "#5676a6", "secondary": "#88a1c2", "accent": "#d8e0f0"}
            if "red" in color_name:
                return {"primary": "#9d514f", "secondary": "#c98881", "accent": "#efd2c9"}
            if "green" in color_name:
                return {"primary": "#6b8966", "secondary": "#97b18f", "accent": "#d6e3d3"}
            if "white" in color_name or "cream" in color_name:
                return {"primary": "#d8d0c4", "secondary": "#f0e8de", "accent": "#b7aa98"}
        if hue < 51:
            return {"primary": "#7b624d", "secondary": "#ac9075", "accent": "#e5d0b7"}
        if hue < 102:
            return {"primary": "#6b7f95", "secondary": "#97adbf", "accent": "#d8e4ee"}
        if hue < 153:
            return {"primary": "#7d6a8e", "secondary": "#a895ba", "accent": "#e4dbef"}
        if hue < 204:
            return {"primary": "#866550", "secondary": "#b48a71", "accent": "#ecd6c8"}
        return {"primary": "#5b7a67", "secondary": "#86a590", "accent": "#d7e4da"}

    @staticmethod
    def _body_metrics(avatar: UserAvatar, *, view: str) -> dict[str, float | str]:
        measurements = avatar.measurements
        profile = avatar.body_profile if getattr(avatar, "body_profile", None) else BodyProfile()
        chest = measurements.chest_cm or 94.0
        waist = measurements.waist_cm or 80.0
        hips = measurements.hips_cm or 96.0
        shoulder = measurements.shoulder_width_cm or 42.0
        quick_anchor = profile.posture_hint == "single_photo"
        anchor_blend = max(0.0, 0.42 - profile.profile_confidence * 0.35) if quick_anchor else 0.0
        head_rx = 70 if view == "side" else 74
        head_ry = 90 if view == "side" else 94
        shoulder_width = min(max(shoulder * 4.0 * profile.shoulder_scale, 144.0), 240.0)
        chest_width = min(max(chest * 2.05 * ((profile.shoulder_scale + profile.waist_scale) / 2.0), 164.0), 270.0)
        waist_width = min(max(waist * 1.9 * profile.waist_scale, 128.0), 232.0)
        hip_width = min(max(hips * 2.0 * profile.hip_scale, 150.0), 258.0)
        if anchor_blend:
            shoulder_width = shoulder_width * (1.0 - anchor_blend) + 190.0 * anchor_blend
            chest_width = chest_width * (1.0 - anchor_blend) + 212.0 * anchor_blend
            waist_width = waist_width * (1.0 - anchor_blend) + 170.0 * anchor_blend
            hip_width = hip_width * (1.0 - anchor_blend) + 210.0 * anchor_blend
        if view == "side":
            shoulder_width *= 0.58 * profile.depth_scale
            chest_width *= 0.56 * profile.depth_scale
            waist_width *= 0.55 * profile.depth_scale
            hip_width *= 0.58 * profile.depth_scale
        torso_top = 330
        torso_bottom = torso_top + int(420 + (profile.torso_length_ratio - 0.36) * 520)
        center = 384
        torso_path = (
            f"M {center - shoulder_width / 2:.1f} {torso_top} "
            f"C {center - chest_width / 2:.1f} 430, {center - waist_width / 2:.1f} 590, {center - hip_width / 2:.1f} {torso_bottom} "
            f"L {center + hip_width / 2:.1f} {torso_bottom} "
            f"C {center + waist_width / 2:.1f} 590, {center + chest_width / 2:.1f} 430, {center + shoulder_width / 2:.1f} {torso_top} Z"
        )
        arm_span = shoulder_width / 2 + (62 if view == "side" else 94)
        arm_left = (
            f"M {center - shoulder_width / 2:.1f} 370 "
            f"C {center - arm_span:.1f} 410, {center - arm_span + 10:.1f} 630, {center - arm_span + 22:.1f} 776 "
            f"L {center - arm_span + 54:.1f} 778 "
            f"C {center - arm_span + 36:.1f} 640, {center - arm_span + 46:.1f} 460, {center - shoulder_width / 2 + 18:.1f} 392 Z"
        )
        arm_right = (
            f"M {center + shoulder_width / 2:.1f} 370 "
            f"C {center + arm_span:.1f} 410, {center + arm_span - 10:.1f} 630, {center + arm_span - 22:.1f} 776 "
            f"L {center + arm_span - 54:.1f} 778 "
            f"C {center + arm_span - 36:.1f} 640, {center + arm_span - 46:.1f} 460, {center + shoulder_width / 2 - 18:.1f} 392 Z"
        )
        leg_gap = 16 if view == "side" else 22
        leg_width = 48 if view == "side" else 54
        leg_end = 804 + int(320 + (profile.leg_length_ratio - 0.48) * 520)
        shoulder_y = torso_top + 16
        waist_y = torso_top + (torso_bottom - torso_top) * 0.56
        hip_y = torso_top + (torso_bottom - torso_top) * 0.82
        knee_y = torso_bottom + (leg_end - torso_bottom) * 0.42
        ankle_y = leg_end - 18
        leg_left = (
            f"M {center - leg_gap - leg_width:.1f} 804 "
            f"C {center - leg_gap - leg_width - 8:.1f} 942, {center - leg_gap - leg_width + 2:.1f} 1080, {center - leg_gap - 6:.1f} {leg_end:.1f} "
            f"L {center - leg_gap + 20:.1f} {leg_end:.1f} "
            f"C {center - leg_gap + 6:.1f} 1048, {center - leg_gap - 2:.1f} 916, {center - leg_gap - 4:.1f} 804 Z"
        )
        leg_right = (
            f"M {center + leg_gap:.1f} 804 "
            f"C {center + leg_gap + 10:.1f} 938, {center + leg_gap + 8:.1f} 1078, {center + leg_gap + leg_width + 8:.1f} {leg_end:.1f} "
            f"L {center + leg_gap + leg_width + 38:.1f} {leg_end:.1f} "
            f"C {center + leg_gap + leg_width + 18:.1f} 1040, {center + leg_gap + leg_width + 8:.1f} 916, {center + leg_gap + leg_width + 2:.1f} 804 Z"
        )
        return {
            "head_rx": head_rx,
            "head_ry": head_ry,
            "torso_path": torso_path,
            "arm_left": arm_left,
            "arm_right": arm_right,
            "leg_left": leg_left,
            "leg_right": leg_right,
            "center": center,
            "chest_width": chest_width,
            "waist_width": waist_width,
            "hip_width": hip_width,
            "shoulder_width": shoulder_width,
            "torso_top": torso_top,
            "torso_bottom": torso_bottom,
            "shoulder_y": shoulder_y,
            "waist_y": waist_y,
            "hip_y": hip_y,
            "knee_y": knee_y,
            "ankle_y": ankle_y,
            "anchor_mode": "quick_photo_stabilized" if quick_anchor else "profile_direct",
        }

    def _avatar_base_svg(self, body: dict[str, float | str]) -> str:
        center = float(body["center"])
        anchor_mode = str(body["anchor_mode"])
        torso_top = float(body["torso_top"])
        torso_bottom = float(body["torso_bottom"])
        hip_width = float(body["hip_width"])
        shadow_width = hip_width + 110
        shadow_y = float(body["ankle_y"]) + 34
        outline_dash = "7 7" if anchor_mode == "quick_photo_stabilized" else "0"
        return (
            f"<ellipse cx='{center:.1f}' cy='{shadow_y:.1f}' rx='{shadow_width / 2:.1f}' ry='24' fill='#d8cabc' opacity='0.42'/>"
            f"<ellipse cx='{center:.1f}' cy='232' rx='{float(body['head_rx']):.1f}' ry='{float(body['head_ry']):.1f}' fill='#d8c5b4'/>"
            f"<path d='{body['torso_path']}' fill='#d8c5b4'/>"
            f"<path d='{body['arm_left']}' fill='#d8c5b4' opacity='0.95'/>"
            f"<path d='{body['arm_right']}' fill='#d8c5b4' opacity='0.95'/>"
            f"<path d='{body['leg_left']}' fill='#d8c5b4'/>"
            f"<path d='{body['leg_right']}' fill='#d8c5b4'/>"
            f"<path d='{body['torso_path']}' fill='none' stroke='#b59f8d' stroke-width='2.5' stroke-dasharray='{outline_dash}' opacity='0.36'/>"
            f"<line x1='{center:.1f}' y1='{torso_top - 28:.1f}' x2='{center:.1f}' y2='{torso_bottom + 8:.1f}' stroke='#b9a997' stroke-width='1.4' opacity='0.18' stroke-dasharray='6 10'/>"
        )

    def _photo_guide_svg(self, body: dict[str, float | str]) -> str:
        center = float(body["center"])
        shoulder_y = float(body["shoulder_y"])
        torso_bottom = float(body["torso_bottom"])
        ankle_y = float(body["ankle_y"])
        return (
            f"<path d='{body['torso_path']}' fill='rgba(255,255,255,0.08)' stroke='#f8eee3' stroke-width='2.2' opacity='0.58'/>"
            f"<path d='{body['arm_left']}' fill='rgba(255,255,255,0.04)' stroke='#f8eee3' stroke-width='1.4' opacity='0.36'/>"
            f"<path d='{body['arm_right']}' fill='rgba(255,255,255,0.04)' stroke='#f8eee3' stroke-width='1.4' opacity='0.36'/>"
            f"<path d='{body['leg_left']}' fill='rgba(255,255,255,0.04)' stroke='#f8eee3' stroke-width='1.4' opacity='0.32'/>"
            f"<path d='{body['leg_right']}' fill='rgba(255,255,255,0.04)' stroke='#f8eee3' stroke-width='1.4' opacity='0.32'/>"
            f"<line x1='{center:.1f}' y1='{shoulder_y - 38:.1f}' x2='{center:.1f}' y2='{ankle_y + 10:.1f}' stroke='#fff7ef' stroke-width='1.2' opacity='0.16' stroke-dasharray='6 8'/>"
            f"<line x1='{center - 120:.1f}' y1='{torso_bottom:.1f}' x2='{center + 120:.1f}' y2='{torso_bottom:.1f}' stroke='#fff7ef' stroke-width='1.2' opacity='0.12' stroke-dasharray='10 10'/>"
        )

    def _photo_replacement_layer(
        self,
        *,
        garment: GarmentItem,
        body: dict[str, float | str],
        palette: dict[str, str],
        overlay_id: str,
        person_mask_id: str | None = None,
    ) -> tuple[str, str]:
        if garment.category not in {
            GarmentCategory.TOP,
            GarmentCategory.OUTERWEAR,
            GarmentCategory.DRESS,
            GarmentCategory.BOTTOM,
            GarmentCategory.FOOTWEAR,
        }:
            return "", "none"
        mask_path = self._expanded_replacement_mask(category=garment.category, body=body, label=garment.title)
        wash_id = f"wash_{quote(overlay_id, safe='')}"
        blur_id = f"blur_{quote(overlay_id, safe='')}"
        person_mask_attr = f" mask='url(#{person_mask_id})'" if person_mask_id else ""
        if garment.category in {GarmentCategory.BOTTOM, GarmentCategory.FOOTWEAR}:
            mode = "lower_body_heuristic"
        elif garment.category == GarmentCategory.DRESS:
            mode = "full_body_heuristic"
        else:
            mode = "upper_body_heuristic"
        return (
            "<defs>"
            f"<linearGradient id='{wash_id}' x1='0' y1='0' x2='0' y2='1'>"
            "<stop offset='0%' stop-color='#f7f1ea' stop-opacity='0.98'/>"
            f"<stop offset='62%' stop-color='{palette['accent']}' stop-opacity='0.74'/>"
            f"<stop offset='100%' stop-color='{palette['secondary']}' stop-opacity='0.42'/>"
            "</linearGradient>"
            f"<filter id='{blur_id}' x='-18%' y='-18%' width='136%' height='136%'><feGaussianBlur stdDeviation='10'/></filter>"
            "</defs>"
            f"<path d='{mask_path}' fill='url(#{wash_id})' opacity='0.90' filter='url(#{blur_id})'{person_mask_attr}/>"
            f"<path d='{mask_path}' fill='#fffaf5' opacity='0.22'{person_mask_attr}/>",
            mode,
        )

    def _expanded_replacement_mask(
        self,
        *,
        category: GarmentCategory,
        body: dict[str, float | str],
        label: str,
    ) -> str:
        center = float(body["center"])
        chest_width = float(body["chest_width"])
        waist_width = float(body["waist_width"])
        hip_width = float(body["hip_width"])
        shoulder_y = float(body["shoulder_y"])
        waist_y = float(body["waist_y"])
        hip_y = float(body["hip_y"])
        ankle_y = float(body["ankle_y"])
        descriptor = label.lower()
        if category == GarmentCategory.TOP:
            width = chest_width + 86
            hem_y = waist_y + (64 if "cropped" in descriptor else 138)
            sleeve_y = shoulder_y + 42
            return (
                f"M {center - width / 2:.1f} {shoulder_y + 6:.1f} "
                f"C {center - width / 2 - 28:.1f} {sleeve_y + 68:.1f}, {center - waist_width / 2 - 24:.1f} {waist_y + 18:.1f}, {center - waist_width / 2 + 2:.1f} {hem_y:.1f} "
                f"L {center + waist_width / 2 - 2:.1f} {hem_y:.1f} "
                f"C {center + waist_width / 2 + 24:.1f} {waist_y + 18:.1f}, {center + width / 2 + 28:.1f} {sleeve_y + 68:.1f}, {center + width / 2:.1f} {shoulder_y + 6:.1f} "
                f"L {center + chest_width / 2 - 8:.1f} {shoulder_y - 28:.1f} L {center - chest_width / 2 + 8:.1f} {shoulder_y - 28:.1f} Z"
            )
        if category == GarmentCategory.OUTERWEAR:
            width = chest_width + 126
            hem_y = hip_y + (42 if "cropped" in descriptor else 148 if "coat" in descriptor else 106)
            return (
                f"M {center - width / 2:.1f} {shoulder_y - 16:.1f} "
                f"C {center - width / 2 - 30:.1f} {waist_y - 18:.1f}, {center - width / 2 - 18:.1f} {hip_y + 12:.1f}, {center - width / 2 + 12:.1f} {hem_y:.1f} "
                f"L {center - 24:.1f} {hem_y:.1f} L {center - 30:.1f} {shoulder_y + 6:.1f} L {center + 30:.1f} {shoulder_y + 6:.1f} L {center + 24:.1f} {hem_y:.1f} "
                f"L {center + width / 2 - 12:.1f} {hem_y:.1f} C {center + width / 2 + 18:.1f} {hip_y + 12:.1f}, {center + width / 2 + 30:.1f} {waist_y - 18:.1f}, {center + width / 2:.1f} {shoulder_y - 16:.1f} Z"
            )
        if category == GarmentCategory.BOTTOM:
            return (
                f"M {center - (hip_width + 96) / 2:.1f} {hip_y - 32:.1f} "
                f"L {center + (hip_width + 96) / 2:.1f} {hip_y - 32:.1f} "
                f"L {center + (hip_width + 96) / 2 - 26:.1f} {float(body['knee_y']):.1f} "
                f"L {center + 56:.1f} {ankle_y + 10:.1f} "
                f"L {center + 4:.1f} {ankle_y + 10:.1f} "
                f"L {center + 10:.1f} {float(body['knee_y']) + 20:.1f} "
                f"L {center - 10:.1f} {float(body['knee_y']) + 20:.1f} "
                f"L {center - 4:.1f} {ankle_y + 10:.1f} "
                f"L {center - 56:.1f} {ankle_y + 10:.1f} "
                f"L {center - (hip_width + 96) / 2 + 26:.1f} {float(body['knee_y']):.1f} Z"
            )
        if category == GarmentCategory.FOOTWEAR:
            return (
                f"M {center - 96:.1f} {ankle_y + 8:.1f} h 74 c 18 0 30 10 36 24 l 10 24 h -108 c -12 0 -20 -8 -20 -18 v -10 c 0 -10 4 -20 8 -20 z "
                f"M {center + 14:.1f} {ankle_y + 8:.1f} h 74 c 18 0 30 10 36 24 l 10 24 h -108 c -12 0 -20 -8 -20 -18 v -10 c 0 -10 4 -20 8 -20 z"
            )
        width = max(chest_width, hip_width) + 92
        return (
            f"M {center - chest_width / 2 - 18:.1f} {shoulder_y - 26:.1f} L {center + chest_width / 2 + 18:.1f} {shoulder_y - 26:.1f} "
            f"C {center + width / 2:.1f} {waist_y - 14:.1f}, {center + width / 2 + 18:.1f} {hip_y + 54:.1f}, {center + width / 2 + 32:.1f} {ankle_y - 38:.1f} "
            f"L {center - width / 2 - 32:.1f} {ankle_y - 38:.1f} C {center - width / 2 - 18:.1f} {hip_y + 54:.1f}, {center - width / 2:.1f} {waist_y - 14:.1f}, {center - chest_width / 2 - 18:.1f} {shoulder_y - 26:.1f} Z"
        )

    def _garment_shape(
        self,
        *,
        category: GarmentCategory,
        body: dict[str, float | str],
        render_mode: str,
        palette: dict[str, str],
        label: str = "",
        role: str | None = None,
        source_kind: str | None = None,
        emphasis: str = "primary",
    ) -> str:
        center = float(body["center"])
        chest_width = float(body["chest_width"])
        waist_width = float(body["waist_width"])
        hip_width = float(body["hip_width"])
        descriptor = f"{label} {role or ''}".lower()
        is_companion = emphasis == "companion"
        base_opacity = 0.76 if render_mode == "wireframe" else (0.82 if is_companion else 0.92)
        opacity = f"{base_opacity:.2f}"
        stroke = palette["accent"]
        fill = "none" if render_mode == "wireframe" else f"{palette['secondary']}"
        detail = palette["primary"]
        outline = "3" if is_companion else "4"
        shoulder_y = float(body["shoulder_y"])
        waist_y = float(body["waist_y"])
        hip_y = float(body["hip_y"])
        knee_y = float(body["knee_y"])
        ankle_y = float(body["ankle_y"])
        if category == GarmentCategory.TOP:
            width = chest_width + (16 if "fitted" in descriptor or "knit" in descriptor else 28)
            hem_y = waist_y + (42 if "cropped" in descriptor else 110)
            sleeve_y = shoulder_y + 36
            return (
                f"<path d='M {center - width / 2:.1f} {shoulder_y + 18:.1f} C {center - width / 2 - 14:.1f} {sleeve_y + 52:.1f}, {center - waist_width / 2 - 8:.1f} {waist_y:.1f}, {center - waist_width / 2 + 6:.1f} {hem_y:.1f} "
                f"L {center + waist_width / 2 - 6:.1f} {hem_y:.1f} C {center + waist_width / 2 + 8:.1f} {waist_y:.1f}, {center + width / 2 + 14:.1f} {sleeve_y + 52:.1f}, {center + width / 2:.1f} {shoulder_y + 18:.1f} "
                f"L {center + chest_width / 2 - 12:.1f} {shoulder_y - 16:.1f} L {center - chest_width / 2 + 12:.1f} {shoulder_y - 16:.1f} Z' fill='{fill}' stroke='{stroke}' stroke-width='{outline}' opacity='{opacity}'/>"
                f"<path d='M {center - 28:.1f} {shoulder_y - 16:.1f} C {center - 10:.1f} {shoulder_y + 12:.1f}, {center + 10:.1f} {shoulder_y + 12:.1f}, {center + 28:.1f} {shoulder_y - 16:.1f}' fill='none' stroke='{detail}' stroke-width='2.4' opacity='0.55'/>"
                f"<line x1='{center - waist_width / 2 + 20:.1f}' y1='{hem_y - 10:.1f}' x2='{center + waist_width / 2 - 20:.1f}' y2='{hem_y - 10:.1f}' stroke='{detail}' stroke-width='2' opacity='0.35'/>"
            )
        if category == GarmentCategory.BOTTOM:
            width = hip_width + (24 if "tailored" in descriptor or "straight" in descriptor else 38)
            rise_y = hip_y - (24 if "high-rise" in descriptor or "high rise" in descriptor else 8)
            ankle_span = 92 if "straight" in descriptor or "tailored" in descriptor else 112
            return (
                f"<path d='M {center - width / 2:.1f} {rise_y:.1f} L {center + width / 2:.1f} {rise_y:.1f} L {center + width / 2 - 18:.1f} {knee_y:.1f} "
                f"L {center + ankle_span / 2:.1f} {ankle_y:.1f} L {center + 6:.1f} {ankle_y:.1f} L {center + 12:.1f} {knee_y + 18:.1f} L {center - 12:.1f} {knee_y + 18:.1f} "
                f"L {center - 6:.1f} {ankle_y:.1f} L {center - ankle_span / 2:.1f} {ankle_y:.1f} L {center - width / 2 + 18:.1f} {knee_y:.1f} Z' fill='{fill}' stroke='{stroke}' stroke-width='{outline}' opacity='{opacity}'/>"
                f"<line x1='{center - width / 2 + 18:.1f}' y1='{rise_y + 16:.1f}' x2='{center + width / 2 - 18:.1f}' y2='{rise_y + 16:.1f}' stroke='{detail}' stroke-width='2' opacity='0.35'/>"
                f"<line x1='{center:.1f}' y1='{rise_y + 18:.1f}' x2='{center:.1f}' y2='{knee_y + 6:.1f}' stroke='{detail}' stroke-width='1.6' opacity='0.28'/>"
            )
        if category == GarmentCategory.DRESS:
            width = max(chest_width, hip_width) + 40
            return (
                f"<path d='M {center - chest_width / 2 - 10:.1f} {shoulder_y - 10:.1f} L {center + chest_width / 2 + 10:.1f} {shoulder_y - 10:.1f} "
                f"C {center + width / 2:.1f} {waist_y - 26:.1f}, {center + width / 2 + 22:.1f} {hip_y + 48:.1f}, {center + width / 2 + 40:.1f} {ankle_y - 48:.1f} "
                f"L {center - width / 2 - 40:.1f} {ankle_y - 48:.1f} C {center - width / 2 - 22:.1f} {hip_y + 48:.1f}, {center - width / 2:.1f} {waist_y - 26:.1f}, {center - chest_width / 2 - 10:.1f} {shoulder_y - 10:.1f} Z' fill='{fill}' stroke='{stroke}' stroke-width='{outline}' opacity='{opacity}'/>"
                f"<line x1='{center - waist_width / 2:.1f}' y1='{waist_y + 10:.1f}' x2='{center + waist_width / 2:.1f}' y2='{waist_y + 10:.1f}' stroke='{detail}' stroke-width='2' opacity='0.35'/>"
            )
        if category == GarmentCategory.OUTERWEAR:
            width = chest_width + (54 if "cropped" in descriptor else 72)
            hem_y = hip_y + (24 if "cropped" in descriptor else 112 if "coat" in descriptor else 78)
            return (
                f"<path d='M {center - width / 2:.1f} {shoulder_y - 6:.1f} C {center - width / 2 - 22:.1f} {waist_y - 34:.1f}, {center - width / 2 - 8:.1f} {hip_y:.1f}, {center - width / 2 + 10:.1f} {hem_y:.1f} "
                f"L {center - 20:.1f} {hem_y:.1f} L {center - 26:.1f} {shoulder_y + 10:.1f} L {center + 26:.1f} {shoulder_y + 10:.1f} L {center + 20:.1f} {hem_y:.1f} "
                f"L {center + width / 2 - 10:.1f} {hem_y:.1f} C {center + width / 2 + 8:.1f} {hip_y:.1f}, {center + width / 2 + 22:.1f} {waist_y - 34:.1f}, {center + width / 2:.1f} {shoulder_y - 6:.1f} Z' fill='{fill}' stroke='{stroke}' stroke-width='{outline}' opacity='{opacity}'/>"
                f"<line x1='{center:.1f}' y1='{shoulder_y + 8:.1f}' x2='{center:.1f}' y2='{hem_y - 4:.1f}' stroke='{detail}' stroke-width='2.2' opacity='0.5'/>"
                f"<path d='M {center - 26:.1f} {shoulder_y + 10:.1f} L {center - 6:.1f} {waist_y - 20:.1f}' fill='none' stroke='{detail}' stroke-width='2' opacity='0.42'/>"
                f"<path d='M {center + 26:.1f} {shoulder_y + 10:.1f} L {center + 6:.1f} {waist_y - 20:.1f}' fill='none' stroke='{detail}' stroke-width='2' opacity='0.42'/>"
            )
        if category == GarmentCategory.FOOTWEAR:
            return (
                f"<path d='M {center - 88:.1f} {ankle_y + 8:.1f} h 66 c 12 0 20 6 24 16 l 8 20 h -92 c -8 0 -14 -6 -14 -14 v -8 c 0 -8 4 -14 8 -14 z' fill='{fill}' stroke='{stroke}' stroke-width='{outline}' opacity='{opacity}'/>"
                f"<path d='M {center + 18:.1f} {ankle_y + 8:.1f} h 66 c 12 0 20 6 24 16 l 8 20 h -92 c -8 0 -14 -6 -14 -14 v -8 c 0 -8 4 -14 8 -14 z' fill='{fill}' stroke='{stroke}' stroke-width='{outline}' opacity='{opacity}'/>"
                f"<line x1='{center - 80:.1f}' y1='{ankle_y + 34:.1f}' x2='{center - 2:.1f}' y2='{ankle_y + 34:.1f}' stroke='{detail}' stroke-width='2' opacity='0.34'/>"
                f"<line x1='{center + 26:.1f}' y1='{ankle_y + 34:.1f}' x2='{center + 104:.1f}' y2='{ankle_y + 34:.1f}' stroke='{detail}' stroke-width='2' opacity='0.34'/>"
            )
        if category == GarmentCategory.ACCESSORY:
            return (
                f"<path d='M {center - 44:.1f} {shoulder_y + 52:.1f} C {center - 12:.1f} {shoulder_y + 22:.1f}, {center + 12:.1f} {shoulder_y + 22:.1f}, {center + 44:.1f} {shoulder_y + 52:.1f}' fill='none' stroke='{stroke}' stroke-width='7' opacity='0.82'/>"
                f"<circle cx='{center:.1f}' cy='{shoulder_y + 74:.1f}' r='10' fill='{detail}' opacity='0.75'/>"
            )
        width = waist_width + 24
        return (
            f"<rect x='{center - width / 2:.1f}' y='{shoulder_y + 40:.1f}' width='{width:.1f}' height='320' rx='32' fill='{fill}' stroke='{stroke}' stroke-width='{outline}' opacity='{opacity}'/>"
        )

    def _photo_grounded_primary_overlay(
        self,
        *,
        garment: GarmentItem,
        body: dict[str, float | str],
        render_mode: str,
        palette: dict[str, str],
        texture: dict[str, str | int | float] | None,
        overlay_id: str,
        role: str | None = None,
        person_mask_id: str | None = None,
    ) -> tuple[str, str]:
        if texture and garment.category in {
            GarmentCategory.TOP,
            GarmentCategory.OUTERWEAR,
            GarmentCategory.DRESS,
            GarmentCategory.BOTTOM,
            GarmentCategory.FOOTWEAR,
        }:
            textured = self._garment_textured_overlay(
                garment=garment,
                body=body,
                texture=texture,
                palette=palette,
                overlay_id=overlay_id,
                role=role,
                person_mask_id=person_mask_id,
            )
            if textured:
                return textured, "source_image"
        return (
            self._garment_shape(
                category=garment.category,
                body=body,
                render_mode=render_mode,
                palette=palette,
                label=garment.title,
                role=role,
                emphasis="primary",
            ),
            "template_fallback",
        )

    def _garment_textured_overlay(
        self,
        *,
        garment: GarmentItem,
        body: dict[str, float | str],
        texture: dict[str, str | int | float],
        palette: dict[str, str],
        overlay_id: str,
        role: str | None = None,
        person_mask_id: str | None = None,
    ) -> str | None:
        mask_path = self._garment_texture_mask(category=garment.category, body=body, label=garment.title, role=role)
        if not mask_path:
            return None
        region = self._garment_texture_region(category=garment.category, body=body, label=garment.title, role=role)
        clip_id = f"clip_{quote(overlay_id, safe='')}"
        stroke = palette["accent"]
        detail = palette["primary"]
        person_mask_attr = f" mask='url(#{person_mask_id})'" if person_mask_id else ""
        return (
            "<defs>"
            f"<clipPath id='{clip_id}'><path d='{mask_path}'/></clipPath>"
            "</defs>"
            f"<image href='{texture['data_uri']}' x='{region['x']:.1f}' y='{region['y']:.1f}' width='{region['w']:.1f}' height='{region['h']:.1f}' preserveAspectRatio='xMidYMid slice' clip-path='url(#{clip_id})'{person_mask_attr} opacity='0.96'/>"
            f"<path d='{mask_path}' fill='rgba(255,255,255,0.06)' stroke='{stroke}' stroke-width='3.5' opacity='0.92'{person_mask_attr}/>"
            f"<path d='{mask_path}' fill='none' stroke='{detail}' stroke-width='1.4' opacity='0.18' stroke-dasharray='8 8'{person_mask_attr}/>"
        )

    def _garment_texture_mask(
        self,
        *,
        category: GarmentCategory,
        body: dict[str, float | str],
        label: str,
        role: str | None = None,
    ) -> str | None:
        center = float(body["center"])
        chest_width = float(body["chest_width"])
        waist_width = float(body["waist_width"])
        hip_width = float(body["hip_width"])
        descriptor = f"{label} {role or ''}".lower()
        shoulder_y = float(body["shoulder_y"])
        waist_y = float(body["waist_y"])
        hip_y = float(body["hip_y"])
        ankle_y = float(body["ankle_y"])
        if category == GarmentCategory.TOP:
            width = chest_width + (16 if "fitted" in descriptor or "knit" in descriptor else 28)
            hem_y = waist_y + (42 if "cropped" in descriptor else 110)
            sleeve_y = shoulder_y + 36
            return (
                f"M {center - width / 2:.1f} {shoulder_y + 18:.1f} "
                f"C {center - width / 2 - 14:.1f} {sleeve_y + 52:.1f}, {center - waist_width / 2 - 8:.1f} {waist_y:.1f}, {center - waist_width / 2 + 6:.1f} {hem_y:.1f} "
                f"L {center + waist_width / 2 - 6:.1f} {hem_y:.1f} "
                f"C {center + waist_width / 2 + 8:.1f} {waist_y:.1f}, {center + width / 2 + 14:.1f} {sleeve_y + 52:.1f}, {center + width / 2:.1f} {shoulder_y + 18:.1f} "
                f"L {center + chest_width / 2 - 12:.1f} {shoulder_y - 16:.1f} L {center - chest_width / 2 + 12:.1f} {shoulder_y - 16:.1f} Z"
            )
        if category == GarmentCategory.OUTERWEAR:
            width = chest_width + (54 if "cropped" in descriptor else 72)
            hem_y = hip_y + (24 if "cropped" in descriptor else 112 if "coat" in descriptor else 78)
            return (
                f"M {center - width / 2:.1f} {shoulder_y - 6:.1f} "
                f"C {center - width / 2 - 22:.1f} {waist_y - 34:.1f}, {center - width / 2 - 8:.1f} {hip_y:.1f}, {center - width / 2 + 10:.1f} {hem_y:.1f} "
                f"L {center - 20:.1f} {hem_y:.1f} L {center - 26:.1f} {shoulder_y + 10:.1f} L {center + 26:.1f} {shoulder_y + 10:.1f} L {center + 20:.1f} {hem_y:.1f} "
                f"L {center + width / 2 - 10:.1f} {hem_y:.1f} C {center + width / 2 + 8:.1f} {hip_y:.1f}, {center + width / 2 + 22:.1f} {waist_y - 34:.1f}, {center + width / 2:.1f} {shoulder_y - 6:.1f} Z"
            )
        if category == GarmentCategory.DRESS:
            width = max(chest_width, hip_width) + 40
            return (
                f"M {center - chest_width / 2 - 10:.1f} {shoulder_y - 10:.1f} L {center + chest_width / 2 + 10:.1f} {shoulder_y - 10:.1f} "
                f"C {center + width / 2:.1f} {waist_y - 26:.1f}, {center + width / 2 + 22:.1f} {hip_y + 48:.1f}, {center + width / 2 + 40:.1f} {ankle_y - 48:.1f} "
                f"L {center - width / 2 - 40:.1f} {ankle_y - 48:.1f} C {center - width / 2 - 22:.1f} {hip_y + 48:.1f}, {center - width / 2:.1f} {waist_y - 26:.1f}, {center - chest_width / 2 - 10:.1f} {shoulder_y - 10:.1f} Z"
            )
        if category == GarmentCategory.BOTTOM:
            width = hip_width + (24 if "tailored" in descriptor or "straight" in descriptor else 40)
            rise_y = hip_y - (24 if "high-rise" in descriptor or "high rise" in descriptor else 8)
            ankle_span = 92 if "straight" in descriptor or "tailored" in descriptor else 112
            return (
                f"M {center - width / 2:.1f} {rise_y:.1f} L {center + width / 2:.1f} {rise_y:.1f} L {center + width / 2 - 18:.1f} {float(body['knee_y']):.1f} "
                f"L {center + ankle_span / 2:.1f} {ankle_y:.1f} L {center + 6:.1f} {ankle_y:.1f} L {center + 12:.1f} {float(body['knee_y']) + 18:.1f} L {center - 12:.1f} {float(body['knee_y']) + 18:.1f} "
                f"L {center - 6:.1f} {ankle_y:.1f} L {center - ankle_span / 2:.1f} {ankle_y:.1f} L {center - width / 2 + 18:.1f} {float(body['knee_y']):.1f} Z"
            )
        if category == GarmentCategory.FOOTWEAR:
            return (
                f"M {center - 88:.1f} {ankle_y + 8:.1f} h 66 c 12 0 20 6 24 16 l 8 20 h -92 c -8 0 -14 -6 -14 -14 v -8 c 0 -8 4 -14 8 -14 z "
                f"M {center + 18:.1f} {ankle_y + 8:.1f} h 66 c 12 0 20 6 24 16 l 8 20 h -92 c -8 0 -14 -6 -14 -14 v -8 c 0 -8 4 -14 8 -14 z"
            )
        return None

    def _garment_texture_region(
        self,
        *,
        category: GarmentCategory,
        body: dict[str, float | str],
        label: str,
        role: str | None = None,
    ) -> dict[str, float]:
        descriptor = f"{label} {role or ''}".lower()
        center = float(body["center"])
        shoulder_y = float(body["shoulder_y"])
        waist_y = float(body["waist_y"])
        hip_y = float(body["hip_y"])
        chest_width = float(body["chest_width"])
        hip_width = float(body["hip_width"])
        ankle_y = float(body["ankle_y"])
        if category == GarmentCategory.TOP:
            width = chest_width + 96
            height = (waist_y + (42 if "cropped" in descriptor else 110)) - (shoulder_y - 36)
            return {"x": center - width / 2, "y": shoulder_y - 36, "w": width, "h": height}
        if category == GarmentCategory.OUTERWEAR:
            hem_y = hip_y + (24 if "cropped" in descriptor else 112 if "coat" in descriptor else 78)
            width = chest_width + 128
            return {"x": center - width / 2, "y": shoulder_y - 28, "w": width, "h": hem_y - (shoulder_y - 28)}
        if category == GarmentCategory.DRESS:
            width = hip_width + 132
            return {"x": center - width / 2, "y": shoulder_y - 22, "w": width, "h": (ankle_y - 48) - (shoulder_y - 22)}
        if category == GarmentCategory.BOTTOM:
            width = hip_width + 96
            return {"x": center - width / 2, "y": hip_y - 28, "w": width, "h": (ankle_y + 10) - (hip_y - 28)}
        if category == GarmentCategory.FOOTWEAR:
            return {"x": center - 126, "y": ankle_y - 10, "w": 252, "h": 86}
        return {"x": center - chest_width / 2, "y": shoulder_y, "w": chest_width, "h": hip_y - shoulder_y}

    def _capture_asset(self, *, avatar: UserAvatar, view: str) -> dict[str, str | int | float] | None:
        preferred = avatar.assets.side_capture_path if view == "side" and avatar.assets.side_capture_path else avatar.assets.front_capture_path
        if not preferred:
            return None
        return self._browser_image_asset(Path(preferred))

    def _garment_texture_asset(self, garment: GarmentItem) -> dict[str, str | int | float] | None:
        for source_image in garment.source_images:
            if source_image.local_path:
                asset = self._browser_image_asset(Path(source_image.local_path))
                if asset:
                    return asset
        if garment.primary_image_path:
            return self._browser_image_asset(Path(garment.primary_image_path))
        return None

    def _browser_image_asset(self, path: Path) -> dict[str, str | int | float] | None:
        if not path.exists():
            return None
        payload = path.read_bytes()
        inspected_mime, width, height = inspect_image_bytes(payload)
        guessed_mime = inspected_mime or mimetypes.guess_type(str(path))[0] or "application/octet-stream"
        if guessed_mime in {"image/heic", "image/heif"}:
            converted = self._ensure_browser_capture(path)
            if converted:
                path = converted
                payload = path.read_bytes()
                inspected_mime, width, height = inspect_image_bytes(payload)
                guessed_mime = inspected_mime or mimetypes.guess_type(str(path))[0] or "image/jpeg"
        if not guessed_mime.startswith("image/"):
            return None
        if guessed_mime not in {"image/png", "image/jpeg", "image/gif", "image/webp", "image/svg+xml"}:
            return None
        if guessed_mime == "image/svg+xml":
            encoded = quote(payload.decode("utf-8"), safe="/:;,+?=&()#%[]@!$'*")
            data_uri = f"data:{guessed_mime},{encoded}"
        else:
            data_uri = f"data:{guessed_mime};base64,{base64.b64encode(payload).decode('ascii')}"
        return {
            "path": str(path),
            "mime": guessed_mime,
            "width": width or 768,
            "height": height or 1024,
            "data_uri": data_uri,
        }

    @staticmethod
    def _ensure_browser_capture(path: Path) -> Path | None:
        target = path.with_suffix(".preview.jpg")
        if target.exists():
            return target
        try:
            completed = subprocess.run(
                ["sips", "-s", "format", "jpeg", str(path), "--out", str(target)],
                check=False,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
            )
        except OSError:
            return None
        if completed.returncode != 0 or not target.exists():
            return None
        return target

    @staticmethod
    def _photo_layout(width: int, height: int) -> dict[str, float]:
        frame_x = 72.0
        frame_y = 214.0
        frame_w = 624.0
        frame_h = 844.0
        if width <= 0 or height <= 0:
            return {
                "frame_x": frame_x,
                "frame_y": frame_y,
                "frame_w": frame_w,
                "frame_h": frame_h,
                "image_x": frame_x,
                "image_y": frame_y,
                "image_w": frame_w,
                "image_h": frame_h,
            }
        scale = min(frame_w / width, frame_h / height)
        image_w = width * scale
        image_h = height * scale
        image_x = frame_x + (frame_w - image_w) / 2
        image_y = frame_y + (frame_h - image_h) / 2
        return {
            "frame_x": frame_x,
            "frame_y": frame_y,
            "frame_w": frame_w,
            "frame_h": frame_h,
            "image_x": image_x,
            "image_y": image_y,
            "image_w": image_w,
            "image_h": image_h,
        }

    def _photo_body_metrics(
        self,
        avatar: UserAvatar,
        *,
        view: str,
        layout: dict[str, float],
    ) -> dict[str, float | str]:
        analysis = self._load_vision_analysis(avatar, view=view)
        if analysis:
            metrics = self._photo_body_metrics_from_vision(
                avatar=avatar,
                view=view,
                layout=layout,
                analysis=analysis,
            )
            if metrics:
                return metrics
        profile = avatar.body_profile if getattr(avatar, "body_profile", None) else BodyProfile()
        quick_anchor = profile.posture_hint == "single_photo"
        anchor_blend = max(0.0, 0.46 - profile.profile_confidence * 0.36) if quick_anchor else 0.0
        image_x = layout["image_x"]
        image_y = layout["image_y"]
        image_w = layout["image_w"]
        image_h = layout["image_h"]
        center = image_x + image_w * 0.5
        head_rx = max(38.0, image_w * (0.09 if view == "side" else 0.1))
        head_ry = max(52.0, image_h * 0.075)
        shoulder_width = image_w * (0.31 + (profile.shoulder_scale - 1.0) * 0.12)
        chest_width = image_w * (0.30 + (profile.shoulder_scale - 1.0) * 0.08)
        waist_width = image_w * (0.22 + (profile.waist_scale - 1.0) * 0.08)
        hip_width = image_w * (0.28 + (profile.hip_scale - 1.0) * 0.08)
        if anchor_blend:
            shoulder_width = shoulder_width * (1.0 - anchor_blend) + image_w * 0.33 * anchor_blend
            chest_width = chest_width * (1.0 - anchor_blend) + image_w * 0.31 * anchor_blend
            waist_width = waist_width * (1.0 - anchor_blend) + image_w * 0.24 * anchor_blend
            hip_width = hip_width * (1.0 - anchor_blend) + image_w * 0.29 * anchor_blend
        if view == "side":
            shoulder_width *= 0.6 * profile.depth_scale
            chest_width *= 0.58 * profile.depth_scale
            waist_width *= 0.57 * profile.depth_scale
            hip_width *= 0.6 * profile.depth_scale
        torso_top = image_y + image_h * 0.22
        torso_bottom = image_y + image_h * (0.62 + (profile.torso_length_ratio - 0.36) * 0.12)
        torso_path = (
            f"M {center - shoulder_width / 2:.1f} {torso_top:.1f} "
            f"C {center - chest_width / 2:.1f} {image_y + image_h * 0.34:.1f}, {center - waist_width / 2:.1f} {image_y + image_h * 0.48:.1f}, {center - hip_width / 2:.1f} {torso_bottom:.1f} "
            f"L {center + hip_width / 2:.1f} {torso_bottom:.1f} "
            f"C {center + waist_width / 2:.1f} {image_y + image_h * 0.48:.1f}, {center + chest_width / 2:.1f} {image_y + image_h * 0.34:.1f}, {center + shoulder_width / 2:.1f} {torso_top:.1f} Z"
        )
        arm_span = shoulder_width / 2 + image_w * (0.08 if view == "side" else 0.14)
        arm_left = (
            f"M {center - shoulder_width / 2:.1f} {torso_top + 34:.1f} "
            f"C {center - arm_span:.1f} {image_y + image_h * 0.34:.1f}, {center - arm_span + 12:.1f} {image_y + image_h * 0.53:.1f}, {center - arm_span + 22:.1f} {image_y + image_h * 0.66:.1f} "
            f"L {center - arm_span + 48:.1f} {image_y + image_h * 0.66:.1f} "
            f"C {center - arm_span + 36:.1f} {image_y + image_h * 0.56:.1f}, {center - arm_span + 44:.1f} {image_y + image_h * 0.4:.1f}, {center - shoulder_width / 2 + 16:.1f} {torso_top + 48:.1f} Z"
        )
        arm_right = (
            f"M {center + shoulder_width / 2:.1f} {torso_top + 34:.1f} "
            f"C {center + arm_span:.1f} {image_y + image_h * 0.34:.1f}, {center + arm_span - 12:.1f} {image_y + image_h * 0.53:.1f}, {center + arm_span - 22:.1f} {image_y + image_h * 0.66:.1f} "
            f"L {center + arm_span - 48:.1f} {image_y + image_h * 0.66:.1f} "
            f"C {center + arm_span - 36:.1f} {image_y + image_h * 0.56:.1f}, {center + arm_span - 44:.1f} {image_y + image_h * 0.4:.1f}, {center + shoulder_width / 2 - 16:.1f} {torso_top + 48:.1f} Z"
        )
        leg_gap = image_w * (0.022 if view == "side" else 0.034)
        leg_width = image_w * (0.07 if view == "side" else 0.08)
        leg_end = image_y + image_h * (0.92 + (profile.leg_length_ratio - 0.48) * 0.1)
        knee_y = torso_bottom + (leg_end - torso_bottom) * 0.42
        ankle_y = leg_end - 10
        leg_left = (
            f"M {center - leg_gap - leg_width:.1f} {torso_bottom:.1f} "
            f"C {center - leg_gap - leg_width - 8:.1f} {torso_bottom + image_h * 0.12:.1f}, {center - leg_gap - leg_width + 2:.1f} {knee_y:.1f}, {center - leg_gap - 6:.1f} {leg_end:.1f} "
            f"L {center - leg_gap + 18:.1f} {leg_end:.1f} "
            f"C {center - leg_gap + 6:.1f} {knee_y + 18:.1f}, {center - leg_gap - 2:.1f} {torso_bottom + image_h * 0.14:.1f}, {center - leg_gap - 4:.1f} {torso_bottom:.1f} Z"
        )
        leg_right = (
            f"M {center + leg_gap:.1f} {torso_bottom:.1f} "
            f"C {center + leg_gap + 10:.1f} {torso_bottom + image_h * 0.12:.1f}, {center + leg_gap + 8:.1f} {knee_y:.1f}, {center + leg_gap + leg_width + 8:.1f} {leg_end:.1f} "
            f"L {center + leg_gap + leg_width + 34:.1f} {leg_end:.1f} "
            f"C {center + leg_gap + leg_width + 18:.1f} {knee_y + 12:.1f}, {center + leg_gap + leg_width + 8:.1f} {torso_bottom + image_h * 0.14:.1f}, {center + leg_gap + leg_width + 2:.1f} {torso_bottom:.1f} Z"
        )
        shoulder_y = torso_top + 14
        waist_y = torso_top + (torso_bottom - torso_top) * 0.56
        hip_y = torso_top + (torso_bottom - torso_top) * 0.82
        return {
            "head_rx": head_rx,
            "head_ry": head_ry,
            "torso_path": torso_path,
            "arm_left": arm_left,
            "arm_right": arm_right,
            "leg_left": leg_left,
            "leg_right": leg_right,
            "center": center,
            "chest_width": chest_width,
            "waist_width": waist_width,
            "hip_width": hip_width,
            "shoulder_width": shoulder_width,
            "torso_top": torso_top,
            "torso_bottom": torso_bottom,
            "shoulder_y": shoulder_y,
            "waist_y": waist_y,
            "hip_y": hip_y,
            "knee_y": knee_y,
            "ankle_y": ankle_y,
            "anchor_mode": "quick_photo_stabilized" if quick_anchor else "photo_profile_direct",
        }

    def _load_vision_analysis(self, avatar: UserAvatar, *, view: str) -> dict | None:
        metadata_dir: Path | None = None
        if avatar.assets.body_profile_path:
            metadata_dir = Path(avatar.assets.body_profile_path).parent
        elif avatar.assets.metadata_path:
            metadata_dir = Path(avatar.assets.metadata_path).parent
        if metadata_dir is None:
            return None
        candidates = [metadata_dir / f"vision_{view}.json"]
        if view == "side":
            candidates.append(metadata_dir / "vision_front.json")
        for path in candidates:
            if not path.exists():
                continue
            try:
                payload = json.loads(path.read_text(encoding="utf-8"))
            except (OSError, json.JSONDecodeError):
                continue
            if payload.get("status") == "ok" and payload.get("points"):
                return payload
        return None

    def _load_segmentation_analysis(self, avatar: UserAvatar, *, view: str) -> dict | None:
        metadata_dir: Path | None = None
        if avatar.assets.body_profile_path:
            metadata_dir = Path(avatar.assets.body_profile_path).parent
        elif avatar.assets.metadata_path:
            metadata_dir = Path(avatar.assets.metadata_path).parent
        if metadata_dir is None:
            return None
        candidates = [metadata_dir / f"segmentation_{view}.json"]
        if view == "side":
            candidates.append(metadata_dir / "segmentation_front.json")
        for path in candidates:
            if not path.exists():
                continue
            try:
                payload = json.loads(path.read_text(encoding="utf-8"))
            except (OSError, json.JSONDecodeError):
                continue
            if payload.get("status") == "ok" and payload.get("mask_path"):
                return payload
        return None

    def _person_mask_svg(
        self,
        *,
        segmentation: dict | None,
        layout: dict[str, float],
    ) -> tuple[str, str | None, str]:
        if not segmentation or not segmentation.get("mask_path"):
            return "", None, "none"
        mask_asset = self._browser_image_asset(Path(segmentation["mask_path"]))
        if not mask_asset:
            return "", None, "none"
        mask_id = f"person_mask_{hashlib.sha1(str(segmentation['mask_path']).encode('utf-8')).hexdigest()[:10]}"
        defs = (
            f"<mask id='{mask_id}'>"
            "<rect width='100%' height='100%' fill='black'/>"
            f"<image href='{mask_asset['data_uri']}' x='{layout['image_x']:.1f}' y='{layout['image_y']:.1f}' width='{layout['image_w']:.1f}' height='{layout['image_h']:.1f}' preserveAspectRatio='none'/>"
            "</mask>"
        )
        return defs, mask_id, "person_segmentation"

    def _photo_body_metrics_from_vision(
        self,
        *,
        avatar: UserAvatar,
        view: str,
        layout: dict[str, float],
        analysis: dict,
    ) -> dict[str, float | str] | None:
        profile = avatar.body_profile if getattr(avatar, "body_profile", None) else BodyProfile()
        points = analysis.get("points") or {}
        left_shoulder = self._vision_canvas_point(points, "leftShoulder", layout)
        right_shoulder = self._vision_canvas_point(points, "rightShoulder", layout)
        left_hip = self._vision_canvas_point(points, "leftHip", layout)
        right_hip = self._vision_canvas_point(points, "rightHip", layout)
        if not (left_shoulder and right_shoulder and left_hip and right_hip):
            return None
        image_y = layout["image_y"]
        image_h = layout["image_h"]
        center = (left_shoulder[0] + right_shoulder[0] + left_hip[0] + right_hip[0]) / 4.0
        shoulder_y = (left_shoulder[1] + right_shoulder[1]) / 2.0
        hip_y = (left_hip[1] + right_hip[1]) / 2.0
        shoulder_width = abs(right_shoulder[0] - left_shoulder[0]) * 1.24
        hip_width = max(abs(right_hip[0] - left_hip[0]) * 1.18, shoulder_width * 0.72)
        chest_width = shoulder_width * 0.9
        waist_width = shoulder_width * 0.62 + hip_width * 0.16
        if view == "side":
            shoulder_width *= 0.68 * profile.depth_scale
            chest_width *= 0.64 * profile.depth_scale
            waist_width *= 0.62 * profile.depth_scale
            hip_width *= 0.68 * profile.depth_scale
        torso_top = shoulder_y - image_h * 0.06
        torso_bottom = hip_y + image_h * 0.08
        waist_y = shoulder_y + (torso_bottom - shoulder_y) * 0.56
        knee_y = self._vision_or_default_y(points, ("leftKnee", "rightKnee"), layout, torso_bottom + image_h * 0.19)
        ankle_y = self._vision_or_default_y(points, ("leftAnkle", "rightAnkle"), layout, image_y + image_h * 0.94)
        leg_gap = layout["image_w"] * (0.022 if view == "side" else 0.034)
        leg_width = layout["image_w"] * (0.07 if view == "side" else 0.08)
        arm_span = shoulder_width / 2 + layout["image_w"] * (0.07 if view == "side" else 0.12)
        torso_path = (
            f"M {center - shoulder_width / 2:.1f} {torso_top:.1f} "
            f"C {center - chest_width / 2:.1f} {shoulder_y + image_h * 0.05:.1f}, {center - waist_width / 2:.1f} {waist_y:.1f}, {center - hip_width / 2:.1f} {torso_bottom:.1f} "
            f"L {center + hip_width / 2:.1f} {torso_bottom:.1f} "
            f"C {center + waist_width / 2:.1f} {waist_y:.1f}, {center + chest_width / 2:.1f} {shoulder_y + image_h * 0.05:.1f}, {center + shoulder_width / 2:.1f} {torso_top:.1f} Z"
        )
        arm_left = (
            f"M {center - shoulder_width / 2:.1f} {torso_top + 26:.1f} "
            f"C {center - arm_span:.1f} {shoulder_y + image_h * 0.02:.1f}, {center - arm_span + 12:.1f} {shoulder_y + image_h * 0.22:.1f}, {center - arm_span + 24:.1f} {torso_bottom - image_h * 0.02:.1f} "
            f"L {center - arm_span + 50:.1f} {torso_bottom - image_h * 0.02:.1f} "
            f"C {center - arm_span + 38:.1f} {shoulder_y + image_h * 0.24:.1f}, {center - arm_span + 44:.1f} {shoulder_y + image_h * 0.08:.1f}, {center - shoulder_width / 2 + 14:.1f} {torso_top + 38:.1f} Z"
        )
        arm_right = (
            f"M {center + shoulder_width / 2:.1f} {torso_top + 26:.1f} "
            f"C {center + arm_span:.1f} {shoulder_y + image_h * 0.02:.1f}, {center + arm_span - 12:.1f} {shoulder_y + image_h * 0.22:.1f}, {center + arm_span - 24:.1f} {torso_bottom - image_h * 0.02:.1f} "
            f"L {center + arm_span - 50:.1f} {torso_bottom - image_h * 0.02:.1f} "
            f"C {center + arm_span - 38:.1f} {shoulder_y + image_h * 0.24:.1f}, {center + arm_span - 44:.1f} {shoulder_y + image_h * 0.08:.1f}, {center + shoulder_width / 2 - 14:.1f} {torso_top + 38:.1f} Z"
        )
        leg_left = (
            f"M {center - leg_gap - leg_width:.1f} {torso_bottom:.1f} "
            f"C {center - leg_gap - leg_width - 8:.1f} {torso_bottom + image_h * 0.12:.1f}, {center - leg_gap - leg_width + 2:.1f} {knee_y:.1f}, {center - leg_gap - 6:.1f} {ankle_y:.1f} "
            f"L {center - leg_gap + 18:.1f} {ankle_y:.1f} "
            f"C {center - leg_gap + 6:.1f} {knee_y + 18:.1f}, {center - leg_gap - 2:.1f} {torso_bottom + image_h * 0.14:.1f}, {center - leg_gap - 4:.1f} {torso_bottom:.1f} Z"
        )
        leg_right = (
            f"M {center + leg_gap:.1f} {torso_bottom:.1f} "
            f"C {center + leg_gap + 10:.1f} {torso_bottom + image_h * 0.12:.1f}, {center + leg_gap + 8:.1f} {knee_y:.1f}, {center + leg_gap + leg_width + 8:.1f} {ankle_y:.1f} "
            f"L {center + leg_gap + leg_width + 34:.1f} {ankle_y:.1f} "
            f"C {center + leg_gap + leg_width + 18:.1f} {knee_y + 12:.1f}, {center + leg_gap + leg_width + 8:.1f} {torso_bottom + image_h * 0.14:.1f}, {center + leg_gap + leg_width + 2:.1f} {torso_bottom:.1f} Z"
        )
        return {
            "head_rx": max(34.0, shoulder_width * 0.33),
            "head_ry": max(48.0, shoulder_width * 0.42),
            "torso_path": torso_path,
            "arm_left": arm_left,
            "arm_right": arm_right,
            "leg_left": leg_left,
            "leg_right": leg_right,
            "center": center,
            "chest_width": chest_width,
            "waist_width": waist_width,
            "hip_width": hip_width,
            "shoulder_width": shoulder_width,
            "torso_top": torso_top,
            "torso_bottom": torso_bottom,
            "shoulder_y": shoulder_y,
            "waist_y": waist_y,
            "hip_y": hip_y,
            "knee_y": knee_y,
            "ankle_y": ankle_y,
            "anchor_mode": "vision_pose_guided",
        }

    @staticmethod
    def _vision_canvas_point(points: dict, key: str, layout: dict[str, float]) -> tuple[float, float] | None:
        point = points.get(key)
        if not point:
            return None
        x = layout["image_x"] + float(point["x"]) * layout["image_w"]
        y = layout["image_y"] + (1.0 - float(point["y"])) * layout["image_h"]
        return x, y

    def _vision_or_default_y(
        self,
        points: dict,
        keys: tuple[str, str],
        layout: dict[str, float],
        default: float,
    ) -> float:
        ys = [canvas[1] for key in keys if (canvas := self._vision_canvas_point(points, key, layout))]
        if not ys:
            return default
        return sum(ys) / len(ys)
